export type Classes = {
    id?: number // Auto-generated by DB on insert
    name: string
    description?: string | null // Can be null in DB
    studentCount: number
    essayCount?: number
    createdAt?: Date | null // Auto-generated by DB, can be null
}
