import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

import { AppSidebar } from '@/components/app-sidebar'

import { Separator } from '@/components/ui/separator'
import { SidebarInset, SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar'
import './globals.css'
import Head from 'next/head'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { Toaster } from 'sonner'
import { ReactQueryProvider } from './react-query-provider'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    icons: {
        icon: '/teachflow-logo.png', // or '/favicon.png' if you used PNG
    },
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    const queryClient = new QueryClient()

    return (
        <html lang="en">
            <Head>
                <link rel="icon" type="image/png" href="/favicon.png" />
                <title>TeachFlow</title>
            </Head>

            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <ReactQueryProvider>
                    <SidebarProvider>
                        <AppSidebar />
                        <SidebarInset>
                            <header className="flex h-16 shrink-0 items-center gap-2 ">
                                <div className="flex items-center gap-2 px-4 ">
                                    <SidebarTrigger className="-ml-1" />
                                    <Separator
                                        orientation="vertical"
                                        className="mr-2 data-[orientation=vertical]:h-4"
                                    />
                                </div>
                            </header>

                            {/* MAIN PAGE */}
                            <div className="flex flex-1 flex-col gap-4 p-4 pt-0">{children}</div>
                        </SidebarInset>
                    </SidebarProvider>
                </ReactQueryProvider>

                <Toaster richColors closeButton position="top-right" />
            </body>
        </html>
    )
}
